apiVersion: v1
kind: Service
metadata:
  name: {{ include "taiga.fullname" . }}-back
  labels:
    {{- toYaml .Values.taigaBack.service.selector | nindent 4 }}
spec:
  type: {{ .Values.taigaBack.service.type }}
  ports:
    - port: {{ .Values.taigaBack.service.port }}
  selector:
    {{- toYaml .Values.taigaBack.service.selector | nindent 4 }}
