apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taiga.fullname" . }}-back
  labels:
    {{- toYaml .Values.taigaBack.selectorLabels | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- toYaml .Values.taigaBack.selectorLabels | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- toYaml .Values.taigaBack.selectorLabels | nindent 8 }}

    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "taiga.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: taiga-back
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.taigaBack.image.repository }}:{{ .Values.taigaBack.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.taigaBack.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: taiga-config
          - secretRef:
              name: taiga-secret
          ports:
            - containerPort: {{ .Values.taigaBack.service.port }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- if .Values.persistence.staticData.enabled }}
            - name: taiga-static-data
              mountPath: {{ .Values.persistence.staticData.mountPath | quote }}
            {{- end }}
            {{- if .Values.persistence.mediaData.enabled }}
            - name: taiga-media-data
              mountPath: {{ .Values.persistence.mediaData.mountPath | quote }}
            {{- end }}
      volumes:
        {{- if .Values.persistence.staticData.enabled }}
        - name: taiga-static-data
          persistentVolumeClaim:
            claimName: taiga-static-data
        {{- end }}
        {{- if .Values.persistence.mediaData.enabled }}
        - name: taiga-media-data
          persistentVolumeClaim:
            claimName: taiga-media-data
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
