apiVersion: v1
kind: Secret
metadata:
  name: taiga-secret
data:
  POSTGRES_USER: "dGFpZ2E="
  POSTGRES_PASSWORD: "dGFpZ2E="
  EMAIL_HOST_USER: "dGFpZ2E="
  EMAIL_HOST_PASSWORD: "dGFpZ2E="
  RABBITMQ_USER: "dGFpZ2E="
  RABBITMQ_PASS: "dGFpZ2E="
  TAIGA_SECRET_KEY: "dGFpZ2Etc2VjcmV0"
