apiVersion: v1
kind: Service
metadata:
  name: {{ include "taiga.fullname" . }}-async-rabbitmq
  labels:
    {{- include "taiga.labels" . | nindent 4 }}
spec:
  type: {{ .Values.taigaAsyncRabbitmq.service.type }}
  ports:
    {{- range .Values.taigaAsyncRabbitmq.service.ports }}
    - port: {{ .port }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- toYaml .Values.taigaAsyncRabbitmq.service.selector | nindent 4 }}
