apiVersion: v1
kind: Service
metadata:
  name: {{ include "taiga.fullname" . }}-db
  labels:
    {{- toYaml .Values.taigaDb.service.selectorLabels | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.taigaDb.service.port }}
  selector:
    {{- toYaml .Values.taigaDb.service.selector | nindent 4 }}
  type: {{ .Values.taigaDb.service.type }}
