apiVersion: v1
kind: Service
metadata:
  name: {{ include "taiga.fullname" . }}-async
  labels:
    {{- include "taiga.labels" . | nindent 4 }}
spec:
  type: {{ .Values.taigaAsync.service.type }}
  ports:
    - port: {{ .Values.taigaAsync.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- toYaml .Values.taigaAsync.service.selector | nindent 4 }}
