apiVersion: v1
kind: Service
metadata:
  name: {{ include "taiga.fullname" . }}-protected
  labels:
    {{- include "taiga.labels" . | nindent 4 }}
spec:
  type: {{ .Values.taigaProtected.service.type }}
  ports:
    - port: {{ .Values.taigaProtected.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- toYaml .Values.taigaProtected.service.selector | nindent 4 }}
